version: 0.1

phases:
  pre_build:
    commands:
      - mkdir aws-cb-test
      - echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g' > latest
  build:
    commands:
      - ./build.sh
      - tar -zcf $(cat latest).tar.gz file
  post_build:
    commands:
      - cp latest aws-cb-test
      - cp $(cat latest).tar.gz aws-cb-test

artifacts:
  files:
    - aws-cb-test/**/*
