version: 0.1

phases:
  build:
    commands:
      - pwd && ls
      - ./build.sh
      - ls
      - mkdir ${CODEBUILD_BUILD_ID}
      - mkdir ${CODEBUILD_BUILD_ID}/subdir
      - touch ${CODEBUILD_BUILD_ID}/subdir/empty
      - echo ${CODEBUILD_BUILD_ID} > latest
      - cp file ${CODEBUILD_BUILD_ID}
      - tar -zcf $(echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g').tar.gz ${CODEBUILD_BUILD_ID}
      - ls

artifacts:
  files:
    - ${CODEBUILD_BUILD_ID}.tar.gz
    - latest
