version: 0.1

phases:
  build:
    commands:
      - pwd && ls
      - ./env.sh
      - ./build.sh
      - ls
      - echo ${BUILD_NUM} > latest
      - tar -zcf ${BUILD_NUM}.tar.gz file
      - ls

artifacts:
  files:
    - latest
    - ${BUILD_NUM}.tar.gz
