version: 0.1

environment_variables:
  plaintext:
    JOB_NAME: "aws-cb-test"

phases:
  build:
    commands:
      - pwd && ls
      - ./build.sh
      - ls
      - mkdir ${JOB_NAME}
      - echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g' > latest
      - tar -zcf $(echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g').tar.gz file
      - cp latest ${JOB_NAME}
      - cp $(echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g').tar.gz ${JOB_NAME}
      - ls

artifacts:
  files:
    - ${JOB_NAME}/**/*
