version: 0.1

phases:
  build:
    commands:
      - pwd && ls
      - ./build.sh
      - ls
      - apt-get install sed
      - echo ${CODEBUILD_BUILD_ID}
      - export BUILDNUM=$(echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g')
      - echo ${BUILDNUM}
      - mkdir ${BUILDNUM}
      - ls

artifacts:
  files:
    - file
