version: 0.1

phases:
  build:
    commands:
      - pwd && ls
      - ./build.sh
      - ls
      - apt-get install sed
      - echo ${CODEBUILD_BUILD_ID}
      - echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g'
      - echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g' > buildnum
      - ls
      - mkdir $(cat buildnum)
      - ls

artifacts:
  files:
    - file
