version: 0.1

phases:
  build:
    commands:
      - pwd && ls
      - ./build.sh
      - ls
      - mkdir ${CODEBUILD_BUILD_ID}
      - echo ${CODEBUILD_BUILD_ID} > latest
      - cp file ${CODEBUILD_BUILD_ID}
      - ls

artifacts:
  files:
    - ${CODEBUILD_BUILD_ID}/**/*
    - latest
