version: 0.1

phases:
  build:
    commands:
      - pwd && ls
      - ./build.sh
      - ls
      - mkdir output
      - mkdir output/subdir
      - touch output/subdir/empty
      - echo ${CODEBUILD_BUILD_ID} > output/latest
      - cp file output/subdir
      - tar -zcf output/$(echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g').tar.gz ${CODEBUILD_BUILD_ID}
      - ls

artifacts:
  files:
    - output/**/*
    - $(echo ${CODEBUILD_BUILD_ID} | sed 's/.*://g').tar.gz
